#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm and use Node.js 20
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 20

npm test
npm run format
npm run lint
git add .